### ISSUE TITLE
do not ship minified Javascript in benchmark.html

### ISSUE THREAD

**Issue by sunweaver** [pvdz/ZeParser#20]
Hi,

I have uploaded a first packaged version of ZeParser (package name: zeparser.js) to Debian and the uploaded package get rejected by the Debian archive's ftpmaster.

The Debian archive ftpmaster who reviewed the package explained what to do with the package to make it get ACCEPTED in Debian:

"""
Please remove the embedded GPLv3 Ext.JS library (among others) in
ZeParser-0.0.7\benchmark.html.

Please replace them with non-minified versions, include it from other parts of
Debian if it is packaged, or remove the benchmark.html file entirely.
"""

I could easily get this issue fixed by getting ZeParser's source tree, removing the benchmark.html file, and re-packing it as tarball which then gets shipped as the source tarball in Debian. 

However, this is awkward. Minified JS in source code is dodgy and should not be executed, anyway. Minified JS code only makes sense if you know the non-minified version that the code was generated from.

Thus, it would be a gain for all if this issue could be fixed upstream:

My suggestion:

  o create a benchmark folder
  o get the .js files you need for benchmark.html from the projects that provide them
    and put them into the benchmark folder
  o move the benchmark.html into that folder, as well
  o remove the minified JS blocks from benchmark.html
  o in benchmark.html: load the JS code from the newly obtained .js files

Do you think that this will be feasible?

Greets,
Mike (aka sunweaver@debian.org)

**Comment by pvdz** [comment]
To be honest, it feels like a lot of changes for a "dead" repository. Especially since I still don't see the point in making a Debian package for a JS library. Add to that the (seemingly) original reason for doing so in the first place; an active-x obfuscator. And you've really got me wondering; why?

I would suggest going the messy route. Just pack everything up in a tarball without the benchmark (which probably should not be included in the first place, anyways). The only files you need are Tokenizer.js, ZeParser.js, and unicodecategories.js .. And maybe the README. You can add whatever license you want/need, it's public domain for all I care.

It's also pretty much dead, unless there's something critical.

**Comment by pvdz** [comment]
Appreciate your efforts though, but it feels like they could be put to better use for packages that are actually useful to Debian :)

I hope one day somebody can explain me the point of arbitrary JavaScript libraries as Debian packages.

**Comment by sunweaver** [comment]
Since the entering of Node.js into Debian unstable *.js projects are handled as libraries.They are packaged as a client-side <somejslib>.js and a Node.js capable node-<somejs4nodelib> package.

The reason for this pickyness is that Debian is realy choosy about software components and how well they go together. Software is shipped in Debian and no other packaging system (npm) is allowed to be used in parallel.

And again: my goal is the packaging of etherpad-lite and making it installable via the dpkg mechanism. Getting such a piece of software also means that it falls into the hands of the Debian QA team and the Debian security team, so the user can rely on security updates whenever such updates are required.

I will package this project without the benchmark.html file.

Thanks,
Mike

**Comment by pvdz** [comment]
Alright, thanks :)
